### ISSUE TITLE
[BUG] scratchpads: excludes = "*" not working correctly

### ISSUE THREAD

**Issue by kuba-gaj** [hyprland-community/pyprland#118]
**Pyprland version**
2.4.0

**Describe the bug**
See the steps below and attached video

**To Reproduce**
I have multiple scratchpads that have `excludes = "*"` set. 
For simplicity i picked 2 of them to show unexpected behaviour: `dropterm` and `top`

1. Everything works fine if I just toggle `term` and `top` (show and hide)
2. Than i show `term` again, and next, without hiding `term` i toggle show `top` - this seems to be working fine, `term` is hidden and only `top` visible
3. Now when I use toggle to hide `top` and `term` surprisingly shows up, and in the wrong place too

**Expected behavior**

after hiding `top` in step 3 no scratchpads should be visible

**Configuration (provide following files/samples when relevant):**

```toml
[scratchpads.dropterm]
animation = "fromTop"
# command = "kitty --class term-drop --config /home/kuba/.config/kitty/qterm.conf tmux new -A -s dropterm"
command = "kitty --class term-drop --config /home/kuba/.config/kitty/qterm.conf tmux attach -d -t dropterm"
class = "term-drop"
size = "90% 90%"
max_size = "1920px 90%"
excludes = "*"

[scratchpads.top]
animation = "fromBottom"
command = "kitty --class kitty_btm --config ~/.config/kitty/qterm.conf btm"
class = "kitty_btm"
size = "90% 90%"
max_size = "1920px 90%"
excludes = "*"

```

**Additional context**

https://github.com/hyprland-community/pyprland/assets/3915056/2a9327cd-ed07-4b7e-b275-679fb104b3b5
