### ISSUE TITLE
[BUG] [scratchpads] Abnormal window position in special workspace with animation fromTop and formBottom 

### ISSUE THREAD

**Issue by Asthestarsfalll** [hyprland-community/pyprland#138]
**Pyprland version**
Which version did you use? (copy & paste the string returned by `pypr version`)

2.4.0

**Describe the bug**

When toggling a scratchpad in a special workspace, the window position is abnormal. And it only happens on the vertical.

https://github.com/user-attachments/assets/03eafcb0-2e4a-4c0f-b5b0-4f8dd15d5427

It seems the ture window still in the correct position, but it shows in a wrong position. I can draw it in the original position:

https://github.com/user-attachments/assets/22c64e8d-bbdc-4683-979f-de909171748c

**To Reproduce**
just toggle scratchpads in sepcial workspace.

**Configuration (provide following files/samples when relevant):**
- pyprland.toml
```toml
[scratchpads.term]
animation = "fromTop"
command = "kitty --class kitty-dropterm"
class = "kitty-dropterm"
size = "75% 60%"
max_size = "1920px 100%"
margin = 50
multi = false

[scratchpads.filemanager]
animation = "fromLeft"
command = "dolphin"
size = "75% 70%"
margin = 50
multi = false
lazy = true
skip_windowrules = ["aspect"]

[scratchpads.music]
animation = "fromBottom"
command = "yesplaymusic"
class = "yesplaymusic"
size = "70% 60%"
lazy = true
multi = false

[scratchpads.obsidian]
animation = "fromRight"
command = "obsidian"
class = "obsidian"
size = "80% 80%"
lazy = true
multi = false
```
- hyprland.conf

**Additional context**

Hyprland version:

```
Hyprland, built from branch main at commit 293e687389a19b369f312c5c335c9afe7c886be1  (renderer: Make shader time always count from zero (6903)).
Date: Wed Jul 17 04:03:10 2024
Tag: v0.41.2-43-g293e6873, commits: 4929

flags: (if any)
```
