### ISSUE TITLE
[FEAT] Catgory for new scratchpad defaults values?

### ISSUE THREAD

**Issue by Icy-Thought** [hyprland-community/pyprland#140]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
A more concise way for setting default values for the ever-growing list of scratchpads without having to add the "default" entries to all the scratchpads`.

**Describe alternatives you've considered**
Writing manual solutions in all the definitions for my scratchpads.

**Additional context**
Examples would be making this possible through adding the new default values under `[scratchpad.settings]` or `[scratchpads.config]`.

**Comment by fdev31** [comment]
Sounds like a good idea.
I'll look into that.
Thank you!

**Comment by fdev31** [comment]
absolutely untested, but if you have a chance to test the git version, you have some "inherit" option which will source a scratchpad or a list of scratchpads...
I may need to allow "no command" in scratchpads...

**Comment by Icy-Thought** [comment]
Thank you so much for accepting the proposal! :)

I will experiment with this either later today or tomorrow after I figure out why some scratchpad animations are slow. (driving me a little insane ngl)

**Comment by Icy-Thought** [comment]
I might've misunderstood the use of this new feature, but is this how you use it?
```toml
[scratchpad.template]
lazy = true
size = "95% 95%"
margin = 25
# animation = "fromTop"
hide_delay = 0.0

[scratchpads.System-Monitor]
inherit = "template"
command = "kitty --class system-monitor -e btop"
class = "system-monitor"
```

**Comment by fdev31** [comment]
ok, two things here, I fixed a small bug in the code which was probably preventing it to work.
Also in your example, it should be "scratchpads" not "scratchpad" on the first line.

Hope the next test will show better, it looks okay for me at the moment.

**Comment by fdev31** [comment]
I just made a couple of fixes and also renamed "inherit" to "use", as in:

```toml
[scratchpads.template]
animation = "fromLeft"

[scratchpads.myrealscratchpad]
use = "template"
```
