### ISSUE TITLE
[BUG] client window not found: after using killactive keybind on a scratchpad

### ISSUE THREAD

**Issue by MartinLoeper** [hyprland-community/pyprland#162]
**Pyprland version**
2.4.3

**Describe the bug**
```toml
[scratchpads.displays]
command = "wdisplays"
animation = "fromLeft"
class = "wdisplays"
size = "70% 70%"
excludes = "*"
lazy = true
margin = 90
multi = false
```

When I kill the scratchpad above using killactive command via a hyprland keybinding, it renders pypr scratchpad unusable until I bring back the scratchpad I just killed.

All scratchpad trigger the error "client window not found" until I bring back the scratchpad above.

**To Reproduce**
1. Add the scratchpad config described above
2. Open the scratchpad called displays
3. Kill it using hyprland's killactive
4. Try to open another scratchpad - not the displays one from above

**Expected behavior**
The scratchpad should open without triggering an error. Just like displays scratchpad would open without an error.

**Configuration (provide following files/samples when relevant):**
- pyprland.toml - see above
- hyprland.conf: `bind = $mainMod, Q, killactive`
