### ISSUE TITLE
[BUG]  When running a scratchpad terminal it is not floating

### ISSUE THREAD

**Issue by Adnan-Malik-26** [hyprland-community/pyprland#166]
**Pyprland version**
2.4.4-6

**Describe the bug**
When running the pyprland terminal the following error can be seen on terminal
```
FAILED b'Invalid rulev2 syntax: ^(kitty-dropterm)$Invalid rulev2 syntax: ^(kitty-dropterm)$Invalid rule'
FAILED b'Invalid rulev2 syntax: ^(kitty-dropterm)$'
FAILED b'Window does not qualify to be **pinned'**
```

**To Reproduce**
I don't know how anyone would reproduce this error

**Expected behavior**
when running a terminal it shows as a floating window

**Configuration (provide following files/samples when relevant):**
- pyprland.toml
```toml
[pyprland]
plugins = ["scratchpads"]

[scratchpads.term]
command = "kitty --class kitty-dropterm"
class = "kitty-dropterm"
size = "75% 75%"
max_size = "1920px 100%"
margin = 50
position = "15% 15%"
lazy = true

[scratchpads.bluetooth]
animation = "fromTop"
command = "kitty --class dropterm bluetuith"
class = "dropterm"
size = "50% 25%"
max_size = "1920px 100%"
margin = 50
lazy = true

[scratchpads.yazi]
animation = "fromTop"
command = "kitty --class yazi yazi"
class = "yazi"
size = "50% 70%"
max_size = "1920px 100%"
margin = 50
lazy = true

```
- hyprland.conf
```conf
windowrulev2 = float,class:^firefox$,title:^(Picture-in-Picture)
windowrulev2 = float,class:^zen$,title:^(Picture-in-Picture)
windowrulev2 = float,title:^(Sign in – Google accounts — Mozilla Firefox)
```
**Additional context**
FAILED b'Invalid rulev2 syntax: ^(kitty-dropterm)$Invalid rulev2 syntax: ^(kitty-dropterm)$Invalid rule'
FAILED b'Invalid rulev2 syntax: ^(kitty-dropterm)$'
FAILED b'Window does not qualify to be pinned'
