### ISSUE TITLE
[BUG] Scratchpad pop-ups behind main window

### ISSUE THREAD

**Issue by AlexAntonik** [hyprland-community/pyprland#173]
**Pyprland version**
2.4.1

**Describe the bug**
When an window from scratchpad launches some sub-widows(like chose file form or some pop-up ) it apears behind main window, so i needed to drag main window around to reach this window. 

**To Reproduce**
1. Launch any app with dialogs or pop-ups in scratchpad(Thunar in my case).
2. Perform action to get second window(open file in thunar)
![Image](https://github.com/user-attachments/assets/7a3a76cf-3c87-4c56-9014-cc31efa51269)
![Image](https://github.com/user-attachments/assets/b023c77a-0339-4f15-ad9a-92503564ecbe)
![Image](https://github.com/user-attachments/assets/b32d88bb-c02c-4d05-a9bd-d63b4fb0b538)
**Expected behavior**
Second window should apear in front fo first one.

**Configuration (provide following files/samples when relevant):**
```nix
{ pkgs, ... }:
{
  home.packages = with pkgs; [ pyprland ];

  home.file.".config/hypr/pyprland.toml".text = ''
    [pyprland]
    plugins = [
      "scratchpads",
      "expose",
    ]

    [scratchpads.term]
    animation = "fromTop"
    command = "ghostty --class=com.mitchellh.ghostty-dropterm"
    class = "com.mitchellh.ghostty-dropterm"
    lazy = true
    size = "76% 70%"
    position= "12% 10%"

    [scratchpads.volume]
    animation = "fromTop"
    command = "pavucontrol"
    class = "pavucontrol"
    lazy = true
    size = "40% 90%"

    [scratchpads.yazi]
    animation = "fromBottom"
    command = "ghostty -e yazi"
    class = "com.mitchellh.ghostty"
    position = "2% 6%"
    size = "96% 92%"

    [scratchpads.telegram-desktop]
    animation = "fromTop"
    command = "telegram-desktop"
    class = "org.telegram.desktop"
    position = "2% 6%"
    size = "96% 92%"

    [scratchpads.thunar]
    animation = "fromBottom"
    command = "thunar"
    class = "thunar"
    size = "75% 70%"
  '';
}
```

**Additional context**
It apears that window correctly attaches to workspace and shifts fokus but stil apears behind. On 2.4.5 same behavior.

**Comment by fdev31** [comment]
It seems to be a limitation, allowing `pinned` and `multi-window` support on the same scratch is conflicting. A fix may degrade performances...
Do you enjoy/need the pinned mode ? then try to set `pinned = false` on this scratchpad....
Maybe I should set pinned= false by default, and raise a warning in case it's enabled with multi window support....

**Comment by AlexAntonik** [comment]
Thx for helping out. Tried `pinned = false` and all works as expected. 
For me prob fine without pinned, but in general sense workflow in pinned more straightforward.

Also tried `unfocus = "hide"` to hide scratchpad if i on another workplace and runned in some issues:
1) If i close and reopen same scratchpad with 2 windows secondory window will be behind primary. 
2) If opened second window all scratchpad will hide and perfomance of my system just drop to the ground. If manually close scratchpad with 2 windows perfomance stays good.(I know there `hysteresis` but some secondary windows need to stay open for a while so this is not helping for me)
There some logs when perfomance drops:
```
QWaylandGLContext::makeCurrent: eglError: 0x3009, this: 0x762444696340

qt.gui.imageio.jpeg: Corrupt JPEG data: premature end of data segment
qt.qpa.wayland.textinput: virtual void QtWaylandClient::QWaylandTextInputv3::disableSurface(wl_surface*) Try to disable surface 0x7624735a7a20 with focusing surface 0x7624bc546580
qt.qpa.wayland.textinput: virtual void QtWaylandClient::QWaylandTextInputv3::disableSurface(wl_surface*) Try to disable surface 0x7624793b0ec0 with focusing surface 0x7624bc546580
qt.qpa.wayland.textinput: virtual void QtWaylandClient::QWaylandTextInputv3::disableSurface(wl_surface*) Try to disable surface 0x7624793b0ec0 with focusing surface 0x7624bc546580
qt.qpa.wayland.textinput: virtual void QtWaylandClient::QWaylandTextInputv3::disableSurface(wl_surface*) Try to disable surface 0x762472823aa0 with focusing surface 0x7624bc546580
```

**Comment by fdev31** [comment]
do you mean the zorder of the attached windows may change when you close & open some scratchpad ?

About the performances, it's hard to tell why, especially the logs are unrelated to pyprland, I guess one of the apps you are using gets wild and starts using all the resources, can you confirm with something like top ?

**Comment by AlexAntonik** [comment]
> do you mean the zorder of the attached windows may change when you close & open some scratchpad ?

Yes.

> About the performances, it's hard to tell why, especially the logs are unrelated to pyprland, I guess one of the apps you are using gets wild and starts using all the resources, can you confirm with something like top ?

Checked btop and nothing eating resources, like only 5% of load, but system unresponsive as hell. Also i set `hysteresis` to 50 secs and seems that performance issue is gone.



One more small bug found: when i open second window with `unfocus` set it will close whole scratchpad because  focus from primary window shifted to secondary

**Comment by fdev31** [comment]
Can you try to upgrade to 2.4.5, I improved some of the multi-window code there... it will be a better reference to raise issues since this code has changed.

On the other hand, regarding hysteresis and performances, it sounds quite surprising (and this code didn't change for a while)... if you set it to 0 (disabled) is it also "fine" regarding performances?

**Comment by fdev31** [comment]
FYI I see some issues with the focus of new windows when autohide is on even on the latest version.

**Comment by fdev31** [comment]
I tried a quick fix but it can't work because I receive Hyprland's event in a reverse order:
the new window gets "active" before it opens.... and I would like avoiding IPC calls and checks on every focusing of a window... do you also see that the new "popup" window gets active before it opens in the logs ?

Should be easy to check using:

```sh
socat - "UNIX-CONNECT:$XDG_RUNTIME_DIR/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock"
```


I get such sequence when opening the "about" popup ("à propos"):

```
activewindow>>nemo-pad,Home
activewindowv2>>563eb5d9b570
destroyworkspace>>special:scratch_filemanager
destroyworkspacev2>>-94,special:scratch_filemanager
windowtitle>>563eb5d7b020
windowtitlev2>>563eb5d7b020,À propos de Nemo
activewindow>>nemo-pad,À propos de Nemo
activewindowv2>>563eb5d7b020
openwindow>>563eb5d7b020,2,nemo-pad,À propos de Nemo
```

**Comment by fdev31** [comment]
If hyprland fixes the event order, I believe such change will improve pyprland's behavior in such scenario:

```diff
diff --git c/pyprland/plugins/scratchpads/__init__.py i/pyprland/plugins/scratchpads/__init__.py
index 77ab823..3cea1db 100644
--- c/pyprland/plugins/scratchpads/__init__.py
+++ i/pyprland/plugins/scratchpads/__init__.py
@@ -441,13 +441,19 @@ class Extension(CastBoolMixin, Plugin):  # pylint: disable=missing-class-docstri
         if item:
             # Ensure initialized (no-op if already initialized)
             await item.initialize(self)
-        elif respawned:
-            # NOTE: for windows which aren't related to the process (see #8)
-            if not await self._alternative_lookup():
-                self.log.info("Updating Scratch info")
-                await self.update_scratch_info()
-            if item and item.meta.should_hide:
-                await self.run_hide(item.uid, flavor=HideFlavors.FORCED)
+        else:
+            if respawned:
+                # NOTE: for windows which aren't related to the process (see #8)
+                if not await self._alternative_lookup():
+                    self.log.info("Updating Scratch info")
+                    await self.update_scratch_info()
+                if item and item.meta.should_hide:
+                    await self.run_hide(item.uid, flavor=HideFlavors.FORCED)
+            else:
+                clients = await self.hyprctl_json("clients")
+                for item in self.scratches.values():
+                    if await self._handle_multiwindow(item, clients):
+                        return
 
     # }}}
     def cancel_task(self, uid: str) -> bool:
@@ -632,9 +638,10 @@ class Extension(CastBoolMixin, Plugin):  # pylint: disable=missing-class-docstri
     async def _handle_multiwindow(self, scratch: Scratch, clients: list[ClientInfo]) -> None:
         """Collect every matching client for the scratchpad and add them to extra_addr if needed."""
         if not self.cast_bool(scratch.conf.get("multi"), True):
-            return
+            return False
         match_by, match_value = scratch.get_match_props()
         match_fn = get_match_fn(match_by, match_value)
+        hit = False
         for client in clients:
             if client["address"] == scratch.full_address:
                 continue
@@ -642,6 +649,8 @@ class Extension(CastBoolMixin, Plugin):  # pylint: disable=missing-class-docstri
                 address = client["address"]
                 if address not in scratch.extra_addr:
                     scratch.extra_addr.add(address)
+                    hit = True
+        return hit
 
     async def _show_transition(self, scratch: Scratch, monitor: MonitorInfo, was_alive: bool) -> None:
         """Performs the transition to visible state."""

```

**Comment by AlexAntonik** [comment]
Tried all on 2.4.5 and seems that all performance issues gone(probably, tried 0,1,50 hysteresis values and all good). But zorder changes as on 2.4.1 and `unfocus` still hides whole scratchpad when second window opens.

As for a natural feel of things.  I wanted `unfocus` to hide scratchpad when i go to another workspace or switched to another window. But it also hides whole scratchpad on any sub window opens so it feels a bit off. And `hysteresis` do not really help, for me this problem arise in case of telegram media viewing(Telegram uses separate window for that) or when i open some file in explorer to quick look, so depending on what i'm doing `hysteresis` need be some what small or pretty big. 

If issue with unfocus resolves for me prob it's will be better to use pypr this way rather than pinned.


> do you also see that the new "popup" window gets active before it opens in the logs ?

Yes, i have same behavior. (Hyprland 0.45.2)
```
windowtitle>>32a82e00
windowtitlev2>>32a82e00,Media viewer
urgent>>32a82e00
urgent>>32a82e00
urgent>>32a82e00
urgent>>32a82e00
activewindow>>org.telegram.desktop,Media viewer
activewindowv2>>32a82e00
fullscreen>>1
openwindow>>32a82e00,1,org.telegram.desktop,Media viewer
createworkspace>>special:scratch_telegram-desktop
createworkspacev2>>-94,special:scratch_telegram-desktop
movewindow>>3291a770,special:scratch_telegram-desktop
movewindowv2>>3291a770,-94,special:scratch_telegram-desktop
fullscreen>>0
movewindow>>32a82e00,special:scratch_telegram-desktop
movewindowv2>>32a82e00,-94,special:scratch_telegram-desktop
fullscreen>>1
```

**Comment by fdev31** [comment]
I'm glad the performances problem is gone!

> still hides whole scratchpad when second window opens

This is because Hyprland focuses the window before it's created (and known to pyprland), I can't easily fix it without a proper order of the emitted events.
Let's see if the discussion makes any progress... else I'll try to think about a workaround but it's not very welcome because it would complicate things a lot and I already have many options/settings to consider when making any change...

**Comment by fdev31** [comment]
It's low prio, but we have some bug to track now 👍  https://github.com/hyprwm/Hyprland/issues/10337

**Comment by fdev31** [comment]
Hm, this was the only fix I was waiting for ;)
I thought the race condition fix would also fix your scenario...

So it's only if you use `pinned=true` as far as I understood... With the logs on this specific use case I'll try to wrap my head around it again... see if I can remove this limitation now (and that events are received in a correct order)

**Comment by fdev31** [comment]
unfocus="hide" works for me on "sub-windows" - I am not sure to understand your scenario, would you be able to make a video or a detailed description for me?

I suspect you are using an app which has sub-windows which are not having the same class as the main one... or there is no class provided in the config, or something like this.

**Comment by AlexAntonik** [comment]
Here main and subwindow 
```
Window 36c1ad10 -> (35) Kotlin Multiplatform Broadcast – (105587):
        mapped: 1
        hidden: 0
        at: 720,0
        size: 720,780
        workspace: 5 (5)
        floating: 0
        pseudo: 0
        monitor: 0
        class: org.telegram.desktop
        title: (35) Kotlin Multiplatform Broadcast – (105587)
        initialClass: org.telegram.desktop
        initialTitle: Telegram
        pid: 21962
        xwayland: 0
        pinned: 0
        fullscreen: 0
        fullscreenClient: 0
        grouped: 0
        tags: im*
        swallowing: 0
        focusHistoryID: 1
        inhibitingIdle: 0
        xdgTag:
        xdgDescription:

Window 368ea950 -> Media viewer:
        mapped: 1
        hidden: 0
        at: 797,51
        size: 1238,696
        workspace: 5 (5)
        floating: 1
        pseudo: 0
        monitor: 0
        class: org.telegram.desktop
        title: Media viewer
        initialClass: org.telegram.desktop
        initialTitle: Media viewer
        pid: 21962
        xwayland: 0
        pinned: 0
        fullscreen: 0
        fullscreenClient: 0
        grouped: 0
        tags: im*
        swallowing: 0
        focusHistoryID: 2
        inhibitingIdle: 0
        xdgTag:
        xdgDescription:
```

**Comment by fdev31** [comment]
Still reproducible with the latest Hyprland ? https://github.com/hyprwm/Hyprland/discussions/10250 has been closed... it may still require some work on Pyprland side for a fully correct behavior.

**Comment by fdev31** [comment]
Ok so even after restarting thunar... then I guess it's a scenario that can't be fixed, but to confirm it please check the classes of the "modals"... for Nemo it could work because it's preserved:

```
Window 55a14f5c0670 -> Home:
        mapped: 1
        hidden: 0
        at: 1401,1341
        size: 960,864
        workspace: 2 (2)
        floating: 1
        pseudo: 0
        monitor: 0
        class: nemo-pad
        title: Home
        initialClass: nemo-pad
        initialTitle: Home
        pid: 84808
        xwayland: 0
        pinned: 1
        fullscreen: 0
        fullscreenClient: 0
        grouped: 0
        tags: 
        swallowing: 0
        focusHistoryID: 2
        inhibitingIdle: 0
        xdgTag: 
        xdgDescription: 

Window 55a14ea37360 -> À propos de Nemo:
        mapped: 1
        hidden: 0
        at: 1645,1602
        size: 472,341
        workspace: 2 (2)
        floating: 1
        pseudo: 0
        monitor: 0
        class: nemo-pad
        title: À propos de Nemo
        initialClass: nemo-pad
        initialTitle: À propos de Nemo
        pid: 84808
        xwayland: 0
        pinned: 1
        fullscreen: 0
        fullscreenClient: 0
        grouped: 0
        tags: 
        swallowing: 0
        focusHistoryID: 1
        inhibitingIdle: 0
        xdgTag: 
        xdgDescription: 
```
