### ISSUE TITLE
[BUG] Scratchpad stays on screen when hidden after reconnecting monitor

### ISSUE THREAD

**Issue by iliayar** [hyprland-community/pyprland#50]
**Pyprland version**
`2.0.2`

**Describe the bug**
When disconnecting external monitor scratchpad will always stays on screen. When hidden it show on top of all windows and is unable to focus. When shown it behaves as usual. The problem stays after all of: close scratchapd window, `hyprctl reload`, restart pypr. 

**To Reproduce**
1. Scratchpad is shown on external monitor
2. Disconnect monitor
3. Observe wrong behavior on laptop screen. Stays broken after connecting monitor

**Expected behavior**
Behave as usual: hide scratchpad completely

**Configuration (provide following files/samples when relevant):**
- pyprland.toml
  ```toml
      [scratchpads.term-quake]
      command = "wezterm start --class term-quake"
      position = "0% 0%"
      size = "100% 50%"
  ```
- hyprland.conf
  ```
        bind = ,T, exec, pypr toggle term-quake
        bind = ,T, submap, reset
        $term_quake = ^(term-quake)$
        windowrule = workspace special silent,$term_quake
        windowrule = float,$term_quake
  ```

**Additional context**
I was able to fix manually by `hyprctl dispatch togglespecialworkspace scratch_term-quake`. After that works as expected.
