### ISSUE TITLE
[FEAT] How to send commands to the created scratchpads?

### ISSUE THREAD

**Issue by kohane27** [hyprland-community/pyprland#57]
Hello! Hope you're doing well. Thank you for creating pyprland!

## Description

I'm using [scratchpads](https://github.com/hyprland-community/pyprland/wiki/scratchpads):

```toml
[scratchpads.music]
command = "kitty --class kitty_music"
animation = "fromRight"
class = "kitty_music"
size = "20% 60%"
margin = 10
```

After the scratchpads, I'd like to run the command `ncmpcpp` such that I'm dropped straight to my music player.

## What I've Tried

The following command doesn't work:

```bash
command = "kitty --class kitty_music zsh -c 'ncmpcpp'"
```

Any help is much appreciated. Thank you!

**Comment by kohane27** [comment]
`kitty --class kitty_music zsh -i -c 'ncm'` works. Silly me. Thank you again!

**Comment by kohane27** [comment]
I tried to run the command `tmuxp load --yes scratchpad` for the scratchpad. `tmuxp` is a session manager for tmux.
Basically, I want the scratchpad (which is just a kitty terminal) to be inside a tmux session called `scratchpad`.

The following doesn't work however:

```toml
[scratchpads.markdown]
command = "kitty --class kitty_Super_N zsh -i -c 'tmuxp load --yes scratchpad'"
class = "kitty_Super_N"
```

I have the following error:

```bash
✖ pypr
⚠ Failed spawning markdown as proc 534354
"kitty --class kitty_Super_N zsh -i -c 'tmuxp load --yes scratchpad'": The command terminated sucessfully, is it already running?
Failed to show markdown, aborting.
```

Any idea is again, much appreciated. Thank you!
