### ISSUE TITLE
Rofi can't bring `pyprland`-managed `scratchpads` back into focus

### ISSUE THREAD

**Issue by kohane27** [hyprland-community/pyprland#58]
Hello! Hope you're doing well. Sorry it's me again. I'm migrating from Sway and so new to Hyprland, apologies in advance if this is not the right place for this question.

## How to reproduce

Please see the following video:

https://github.com/hyprland-community/pyprland/assets/57322459/fa473565-ca06-4722-b250-3ccaf7025276

1. `rofi -show window`
2. choose `kitty_music`, which is managed by `pyprland`'s `scratchpads`
3. The following happens:
    - `kitty_music` is not brought into focus (I expect it'll be brought into focus)
    - my current window is dimmed; I can't focus back to it and it "freezes"; it doesn't respond to any keystrokes and clicks
4. I have to run `rofi -show window` and choose `kitty_music` again in order to unfreeze my current window

`pyprland.toml`:

```toml
[pyprland]
plugins = [ "scratchpads" ]

[scratchpads.kitty_top]
command = "kitty --class kitty_dropterm --execute tmux attach-session -t misc"
animation = "fromTop"
class = "kitty_dropterm"
size = "50% 45%"
margin = 40

[scratchpads.kitty_right]
command = "kitty --class kitty_music --execute ncmpcpp"
animation = "fromRight"
class = "kitty_music"
size = "20% 60%"
margin = 10
```

# What I have tried

I know (hopefully) how to built-in scratchpad works in hyprland:

```
bind =    $mod,          s,        movetoworkspacesilent, special
```

When I press `$mod, s`, it'll move the current focused window to the special workspace called `special`.
When I run `rofi -show window`, and move the scratchpad back to focus.

But `pyprland`-managed `scratchpads` doesn't seem to work this way?

Any help is much appreciated. Thank you!
